


### Create a new message
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "carl@carl.net",
    "password": "1234"
}


### Get a Particular Messages
GET http://localhost:3000/auth/


