


### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "carl@carl.net",
    "password": "1234"
}


### Get a Particular User with a given ID
GET http://localhost:3000/auth/4


### Get all User with a given email
GET http://localhost:3000/auth?email=carl@carl.net


### Delete a User with a given ID
DELETE http://localhost:3000/auth/1123


### Update a users email
PATCH http://localhost:3000/auth/1123
content-type: application/json

{
    "email": "carlos@carl.net"
}


### Update a users password
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "password": "1235"
}


### Update a users email and password
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "carl@carl.net",
    "password": "1234"
}


### Create a new user (Passing in a content object we can parse)
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "content": {
        "username": "Damian.Wayne@GothamKnight.com",
        "password": "1234",
        "firstName": "damian",
        "lastName": "wayne",
        "phone": "123-123-1234",
        "email": "test@test.com",
        "website": "GothamKnight.com"
    }

}